###
GET http://localhost:7777/users HTTP/1.1
Content-Type: application/json

{}
###
POST  http://localhost:7777/users/ HTTP/1.1
Content-Type: application/json


{
  
  "tipoUsuario": "persona",
  "tipoDocumento": "cedula",
  "numDocumento": 11111,
  "name":"fidel " ,
  "email":"fidel.fuerte@gmail.com",
  "apellido":"fuerte",
  "lastname": "fuerte",
  "razon":"" ,
  "sexo": "masculino",
  "fechaNacimineto":"noviembre" ,
  "ciudad": "tunja",
  "direccion":"cll50#16b-03",
  "barrio": "colinas del norte",
  "correo": "fidel@gmail.com",
  "telefono": 555555,
  "movil": 312555555,
  "estado": "activo",     
  "rol": "administrador"
  }
# ###
# DELETE http://localhost:3000/api/users/616668c1341fcfa7b6c04727 HTTP/1.1
# Content-Type: application/json
 








###

GET http://localhost:7777/users HTTP/1.1
Content-Type: application/json








###

GET http://localhost:7777/users/6167597fb568bc516bc44e9f HTTP/1.1
Content-Type: application/json
###

PUT  http://localhost:3000/api/61677058018ff117932b8beb HTTP/1.1
Content-Type: application/json