###
GET http://localhost:7878/users HTTP/1.1
Content-Type: application/json

{}
###
POST  http://localhost:7878/users/ HTTP/1.1
Content-Type: application/json


{
  "din": 1001,
  "tipoUsuario": "persona",
  "tipoDocumento": "cedula",
  "numDocumento": 101012,
  "name":"MAria" ,
  "lastname": "Perez",
  "razon":"" ,
  "sexo": "Masculino",
  "fechaNacimineto":"Enero" ,
  "ciudad": "Cucuta",
  "direccion":"cucuta",
  "barrio": "cucuta",
  "correo": "antonio@email.com",
  "telefono": 3333333,
  "movil": 3123333333,
  "estado": "Autorizado",     
  "rol": "administrador"
  }

# ###
# DELETE http://localhost:3000/api/users/616668c1341fcfa7b6c04727 HTTP/1.1
# Content-Type: application/json
 








###

GET http://localhost:7878/users/numDocumentos/3333333 HTTP/1.1
Content-Type: application/json








###

GET http://localhost:7878/users/616b937f7fcea9384212b21c HTTP/1.1
Content-Type: application/json
###

PUT  http://localhost:7878/users/61677031018ff117932b8be9 HTTP/1.1
Content-Type: application/json




{}


###
PUT http://localhost:7878/products/ HTTP/1.1
Content-Type: application/json

{




}